commerce_payment.commerce_payment_gateway.plugin.paylike:
  type: commerce_payment_gateway_configuration
  mapping:
    public_key:
      type: string
      label: 'Public API key'
    private_key:
      type: string
      label: 'Private API key'
    payment_method_title:
      type: string
      label: 'Payment method title'
    payment_method_description:
      type: string
      label: 'Payment method description'
    popup_title:
      type: string
      label: 'Payment popup title'
